// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AdType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ad_type");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("area");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("district");

                    b.Property<string>("Metro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("metro");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("RoomCount")
                        .HasColumnType("int")
                        .HasColumnName("room_count");

                    b.Property<string>("SellerType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("seller_type");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("village");

                    b.HasKey("Id");

                    b.ToTable("building", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.BuildingPost", b =>
                {
                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("building_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("BuildingId");

                    b.ToTable("building_post", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.BuildingType", b =>
                {
                    b.Property<Guid>("IdBuildingType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_building_type");

                    b.Property<string>("BuildingTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("building_type_name");

                    b.Property<string>("Keyword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("keyword");

                    b.HasKey("IdBuildingType");

                    b.HasIndex(new[] { "IdBuildingType" }, "IX_building_type");

                    b.ToTable("building_type", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.Document", b =>
                {
                    b.Property<Guid>("IdDocument")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_document");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("document_name");

                    b.Property<string>("Keyword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("keyword");

                    b.Property<string>("Keyword01")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("keyword_01");

                    b.Property<string>("Keyword02")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("keyword_02");

                    b.Property<string>("Keyword03")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("keyword_03");

                    b.HasKey("IdDocument");

                    b.ToTable("document", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.Metro", b =>
                {
                    b.Property<Guid>("IdMetro")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_metro");

                    b.Property<Guid?>("FkIdRegion")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_id_region");

                    b.Property<string>("Keyword01")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("keyword_01");

                    b.Property<string>("Keyword02")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("keyword_02");

                    b.Property<string>("Keyword03")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("keyword_03");

                    b.Property<string>("Keyword04")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("keyword_04");

                    b.Property<string>("Keyword05")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("keyword_05");

                    b.Property<string>("MetroName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("metro_name");

                    b.HasKey("IdMetro");

                    b.HasIndex(new[] { "FkIdRegion" }, "IX_fk_id_region");

                    b.ToTable("metro", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.OperationType", b =>
                {
                    b.Property<Guid>("IdOperationType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_operation_type");

                    b.Property<string>("Keyword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("keyword");

                    b.Property<string>("OperationTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("operation_type_name");

                    b.HasKey("IdOperationType");

                    b.ToTable("operation_type", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.OwnerType", b =>
                {
                    b.Property<Guid>("IdOwnerType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_owner_type");

                    b.Property<string>("Keyword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("keyword");

                    b.Property<string>("OwnerTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("owner_type_name");

                    b.HasKey("IdOwnerType");

                    b.ToTable("owner_type", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.Property", b =>
                {
                    b.Property<Guid>("IdProperty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_property");

                    b.Property<string>("Address")
                        .HasColumnType("ntext")
                        .HasColumnName("address");

                    b.Property<string>("ApprovmentMessage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("approvment_message");

                    b.Property<int?>("ApprovmentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("approvment_status");

                    b.Property<double?>("Area")
                        .HasColumnType("float")
                        .HasColumnName("area");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("CpName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cp_name");

                    b.Property<string>("CpPhoneNumber01")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cp_phone_number_01");

                    b.Property<string>("CpPhoneNumber02")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cp_phone_number_02");

                    b.Property<string>("CpPhoneNumber03")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cp_phone_number_03");

                    b.Property<string>("Data")
                        .HasColumnType("ntext")
                        .HasColumnName("data");

                    b.Property<string>("EX")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ex");

                    b.Property<string>("EY")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ey");

                    b.Property<Guid?>("FkIdBuildingType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_id_building_type");

                    b.Property<Guid?>("FkIdCity")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_id_city");

                    b.Property<Guid?>("FkIdCurrency")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_id_currency");

                    b.Property<Guid?>("FkIdDocument")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_id_document");

                    b.Property<Guid?>("FkIdLink")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkIdMetro")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_id_metro");

                    b.Property<Guid?>("FkIdOperationType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_id_operation_type");

                    b.Property<Guid?>("FkIdOwnerType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_id_owner_type");

                    b.Property<Guid?>("FkIdPropertyType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_id_property_type");

                    b.Property<Guid?>("FkIdRepair")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_id_repair");

                    b.Property<Guid?>("FkIdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkIdSource")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkIdTarget")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_id_target");

                    b.Property<int?>("Floor")
                        .HasColumnType("int")
                        .HasColumnName("floor");

                    b.Property<int?>("FloorOf")
                        .HasColumnType("int")
                        .HasColumnName("floor_of");

                    b.Property<double?>("GeneralArea")
                        .HasColumnType("float")
                        .HasColumnName("general_area");

                    b.Property<string>("Images")
                        .HasColumnType("ntext")
                        .HasColumnName("images");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime")
                        .HasColumnName("insert_date");

                    b.Property<double?>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("float")
                        .HasColumnName("unit_price");

                    b.Property<string>("UploadMessage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("upload_message");

                    b.Property<int?>("UploadStatus")
                        .HasColumnType("int")
                        .HasColumnName("upload_status");

                    b.HasKey("IdProperty");

                    b.HasIndex(new[] { "ApprovmentStatus" }, "IX_property_approvment_status");

                    b.HasIndex(new[] { "Code" }, "IX_property_code")
                        .IsDescending();

                    b.HasIndex(new[] { "CpPhoneNumber01" }, "IX_property_cp_phone_number_01");

                    b.HasIndex(new[] { "CpPhoneNumber02" }, "IX_property_cp_phone_number_02");

                    b.HasIndex(new[] { "CpPhoneNumber03" }, "IX_property_cp_phone_number_03");

                    b.HasIndex(new[] { "FkIdLink" }, "IX_property_fk_id_link");

                    b.HasIndex(new[] { "FkIdOwnerType" }, "IX_property_fk_id_owner_type");

                    b.HasIndex(new[] { "FkIdSource" }, "IX_property_fk_id_source");

                    b.HasIndex(new[] { "InsertDate" }, "IX_property_insert_date")
                        .IsDescending();

                    b.HasIndex(new[] { "UploadStatus" }, "IX_property_upload_status");

                    b.ToTable("property", null, t =>
                        {
                            t.HasTrigger("trg_insert_agency_phone_number");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("EntityLayer.Entities.PropertyType", b =>
                {
                    b.Property<Guid>("IdPropertyType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_property_type");

                    b.Property<string>("PropertyTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("property_type_name");

                    b.HasKey("IdPropertyType");

                    b.ToTable("property_type", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.Region", b =>
                {
                    b.Property<Guid?>("IdRegion")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_region");

                    b.Property<string>("Keyword01")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("keyword_01");

                    b.Property<string>("Keyword02")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("keyword_02");

                    b.Property<string>("Keyword03")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("keyword_03");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("region_code");

                    b.Property<string>("RegionName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("region_name");

                    b.HasKey("IdRegion");

                    b.ToTable("region", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.RegionUnit01", b =>
                {
                    b.Property<Guid?>("IdRegion")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_region");

                    b.Property<string>("Keyword01")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("keyword_01");

                    b.Property<string>("Keyword02")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("keyword_02");

                    b.Property<string>("Keyword03")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("keyword_03");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("region_code");

                    b.Property<string>("RegionName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("region_name");

                    b.HasKey("IdRegion");

                    b.ToTable("region_unit_01", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.RepairRate", b =>
                {
                    b.Property<Guid>("IdRepairRate")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_repair_rate");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("is_active");

                    b.Property<string>("RepairRateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("repair_rate_name");

                    b.HasKey("IdRepairRate");

                    b.ToTable("repair_rate", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.RoomCount", b =>
                {
                    b.Property<Guid>("IdRoomCount")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_room_count");

                    b.Property<string>("Keyword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("keyword");

                    b.Property<string>("RoomCountName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("room_count_name");

                    b.HasKey("IdRoomCount");

                    b.ToTable("room_count", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("contact_number");

                    b.Property<bool>("IsValidate")
                        .HasColumnType("bit")
                        .HasColumnName("is_validate");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("otp_code");

                    b.Property<DateTime>("OtpCreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("otp_created_time");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("password_salt");

                    b.Property<string>("UserMail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("user_mail");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_password");

                    b.HasKey("Id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.BuildingPost", b =>
                {
                    b.HasOne("EntityLayer.Entities.Building", "Building")
                        .WithOne()
                        .HasForeignKey("EntityLayer.Entities.BuildingPost", "BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });
#pragma warning restore 612, 618
        }
    }
}
